[build]
builder = "dockerfile"
dockerfilePath = "./API.Lanchonete/Dockerfile"
dockerContext = "./API.Lanchonete"

[deploy]
startCommand = "dotnet API.Lanchonete.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 100