// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Lanchonete.Domain.Entities;

public partial class ControleAcesso
{
    public int IdControle { get; set; }

    public int IdPerfil { get; set; }

    public string NomeTela { get; set; }

    public bool Permitido { get; set; }

    public DateTime? DataCadastro { get; set; }

    public virtual Perfil IdPerfilNavigation { get; set; }
}