// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Lanchonete.Domain.Entities;

public partial class ItensPedido
{
    public int IdItem { get; set; }

    public int IdPedido { get; set; }

    public int IdProduto { get; set; }

    public int Quantidade { get; set; }

    public string Status { get; set; }

    public DateTime? DataCadastro { get; set; }

    public DateTime? DataAtualizacao { get; set; }

    public virtual Pedido IdPedidoNavigation { get; set; }

    public virtual Produto IdProdutoNavigation { get; set; }
}