// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Lanchonete.Domain.Entities;

public partial class Perfil
{
    public int IdPerfil { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public DateTime? DataCadastro { get; set; }

    public virtual ICollection<ControleAcesso> ControleAcessos { get; set; } = new List<ControleAcesso>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}