// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Lanchonete.Domain.Entities;

public partial class Produto
{
    public int IdProduto { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public decimal Preco { get; set; }

    public string Tipo { get; set; }

    public bool? Ativo { get; set; }

    public DateTime? DataCadastro { get; set; }

    public DateTime? DataAtualizacao { get; set; }

    public virtual ICollection<ItensPedido> ItensPedidos { get; set; } = new List<ItensPedido>();
}