// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Lanchonete.Domain.Entities;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public int IdPerfil { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string SenhaHash { get; set; }

    public string SenhaSalt { get; set; }

    public DateTime? DataCadastro { get; set; }

    public DateTime? DataAtualizacao { get; set; }

    public virtual Perfil IdPerfilNavigation { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}